(() => {
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], storeKey="bbat-box-game-records-v2";
  let league={teamKey:"bbat",leagueId:"seoul",name:"서울 일요리그",editable:true},record=null,editing=null;
  const load=()=>{try{return JSON.parse(localStorage.getItem(storeKey)||"[]")}catch{return[]}},save=a=>localStorage.setItem(storeKey,JSON.stringify(a)),esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
  const teamName=()=>{try{return teams[selectedTeam]?.name||"배트조짐"}catch{return"배트조짐"}},emptyPA=()=>({result:"",balls:0,strikes:0,rbi:0,run:false,bases:[false,false,false],note:""}),batter=(name,number="")=>({name,number,position:"",subs:[],pa:Array.from({length:10},emptyPA)}),pitcher=name=>({name,ip:0,h:0,r:0,er:0,bb:0,so:0,pitches:0,strikes:0,balls:0});
  function screen(name){$$('.app-screen').forEach(s=>{const on=s.dataset.screen===name;s.hidden=!on;s.classList.toggle('active',on)});$$('[data-nav]').forEach(n=>n.classList.toggle('active',n.dataset.nav===(['league-detail','scorebook'].includes(name)?'league':name)));scrollTo(0,0)}
  function rosterPlayers(){try{const list=rosters[selectedTeam].filter(p=>p.isPlayer!==false).map(p=>({name:p.name,number:p.number||"",position:p.position||""}));if(list.length)return list}catch{}return[{number:"23",name:"이도윤",position:"CF"},{number:"7",name:"김민재",position:"SS"},{number:"14",name:"최현우",position:"2B"},{number:"33",name:"장시온",position:"1B"},{number:"2",name:"문태경",position:"C"},{number:"18",name:"박준호",position:"P"},{number:"41",name:"한지우",position:"P"}]}
  function lineupPlayers(){let a=[];try{const g=getUpcomingGames(selectedTeam,league.leagueId)[0],l=g&&lineupState[gameKey(selectedTeam,league.leagueId,g)];if(l?.batting)a=l.batting.map(x=>({name:x.playerName||x.name,number:x.number||"",position:x.position||""}))}catch{}if(!a.length)a=rosterPlayers().slice(0,9);while(a.length<9)a.push({name:`${a.length+1}번 타자`,number:"",position:""});return a.slice(0,9)}
  function fresh(){return{id:`game-${Date.now()}`,teamKey:league.teamKey,leagueId:league.leagueId,date:new Date().toISOString().slice(0,10),opponent:"",ourRuns:0,oppRuns:0,finished:false,ours:lineupPlayers().map(p=>({...batter(p.name,p.number),position:p.position})),opps:Array.from({length:9},(_,i)=>batter("",String(i+1))),ourPitchers:[pitcher("선발투수")],oppPitchers:[pitcher("상대 선발투수")]}}
  function normalize(r){for(const prop of ['ours','opps']){r[prop]=(r[prop]||[]).map((b,i)=>({...batter(b.name||"",b.number||""),...b,subs:b.subs||[],pa:Array.from({length:10},(_,j)=>({...emptyPA(),...(b.pa?.[j]||{})}))}));while(r[prop].length<9)r[prop].push(batter(prop==='ours'?`${r[prop].length+1}번 타자`:"",prop==='opps'?String(r[prop].length+1):""))}r.ourPitchers=(r.ourPitchers||[pitcher("선발투수")]).map(p=>({...pitcher(p.name),...p}));r.oppPitchers=(r.oppPitchers||[pitcher("상대 선발투수")]).map(p=>({...pitcher(p.name),...p}));return r}
  function archive(){const rows=load().filter(r=>r.teamKey===league.teamKey&&r.leagueId===league.leagueId).sort((a,b)=>b.date.localeCompare(a.date));$('#leagueDetailTitle').textContent=league.name;$('#leagueRoleChip').textContent=league.editable?'관리자 · 수정 가능':'보기 전용';$('#startGameRecord').hidden=!league.editable;$('#recordCount').textContent=`기록된 경기 ${rows.length}`;$('#recordedGameList').innerHTML=rows.length?rows.map(r=>`<article class="record-game-card"><div class="record-game-date">${esc(r.date)}<br>${r.finished?'경기 종료':'작성 중'}</div><div class="record-game-match"><strong>${esc(teamName())} vs ${esc(r.opponent||'상대팀')}</strong><span>우리팀 AVG ${r.ourSummary?.avg||'.000'} · 상대팀 AVG ${r.oppSummary?.avg||'.000'}</span></div><div class="record-game-score"><b>${r.ourRuns||0} : ${r.oppRuns||0}</b><button data-record="${r.id}">${league.editable?'기록 수정':'기록 보기'}</button></div></article>`).join(''):'<div class="empty-records"><strong>아직 저장된 경기 기록이 없어요.</strong><p>‘경기 기록’을 눌러 첫 기록을 시작하세요.</p></div>';$$('[data-record]',$('#recordedGameList')).forEach(b=>b.onclick=()=>openBook(b.dataset.record))}
  const results=[['','미정'],['1B','1루타'],['2B','2루타'],['3B','3루타'],['HR','홈런'],['BB','볼넷'],['HBP','사구'],['SO','삼진'],['GO','땅볼'],['FO','뜬공'],['FC','야수선택'],['E','실책'],['SAC','희생타']];
  function diamond(pa){const on=pa.bases||[];return`<span class="mini-diamond"><i class="base-2 ${on[1]?'on':''}"></i><i class="base-3 ${on[2]?'on':''}"></i><i class="base-1 ${on[0]?'on':''}"></i><i class="home ${pa.run?'on':''}"></i></span>`}
  function playerIdentity(side,b,i,disabled){if(side==='ours'){const options=rosterPlayers().map(p=>`<option value="${esc(p.name)}" ${p.name===b.name?'selected':''}>${esc(p.number)} ${esc(p.name)}</option>`).join('');return`<div class="sheet-player"><span class="sheet-order">${i+1}</span><select data-player-name ${disabled?'disabled':''}><option value="${esc(b.name)}">${esc(b.number)} ${esc(b.name)}</option>${options}</select><input data-position value="${esc(b.position)}" placeholder="수비" ${disabled?'disabled':''}></div>`}return`<div class="sheet-player"><span class="sheet-order">${i+1}</span><input class="uniform-no" data-number value="${esc(b.number)}" placeholder="No." ${disabled?'disabled':''}><input data-player-name value="${esc(b.name)}" placeholder="상대 선수 이름" ${disabled?'disabled':''}></div>`}
  function batting(side,a,disabled){return`<div class="paper-scorebook"><div class="paper-head"><div>타순 · 선수</div>${Array.from({length:10},(_,i)=>`<div>${i+1}</div>`).join('')}</div>${a.map((b,i)=>`<section class="paper-player" data-side="${side}" data-i="${i}"><div class="identity-stack">${playerIdentity(side,b,i,disabled)}<div class="substitution-list">${b.subs.map((s,j)=>`<span>${j+1}차 교체 · ${esc(s.name)} ${esc(s.note||'')}</span>`).join('')}</div>${disabled?'':`<button class="add-sub" type="button" data-add-sub>＋ 선수 교체</button>`}</div>${b.pa.map((pa,j)=>`<button class="pa-score-cell ${pa.result?'recorded':''}" type="button" data-open-pa="${j}" ${disabled?'disabled':''}>${diamond(pa)}<strong>${esc(pa.result||'')}</strong><small>B${pa.balls} S${pa.strikes}${pa.rbi?` · ${pa.rbi}타점`:''}</small></button>`).join('')}</section>`).join('')}</div>`}
  function pitching(side,a,disabled){return`<div class="pitch-console">${a.map((p,i)=>`<article class="pitcher-console" data-ps="${side}" data-pi="${i}"><div class="pitcher-title"><input data-pitch="name" value="${esc(p.name)}" ${disabled?'disabled':''}><span>총 <b>${p.pitches}</b>구</span></div><div class="pitch-totals"><div><small>스트라이크</small><strong>${p.strikes}</strong></div><div><small>볼</small><strong>${p.balls}</strong></div><div><small>스트라이크 비율</small><strong>${p.pitches?Math.round(p.strikes/p.pitches*100):0}%</strong></div></div><div class="pitch-actions"><button type="button" data-pitch-add="strike" ${disabled?'disabled':''}>스트라이크</button><button type="button" data-pitch-add="ball" ${disabled?'disabled':''}>볼</button><button type="button" data-pitch-undo ${disabled?'disabled':''}>↶ 취소</button></div><div class="pitch-line">${[['ip','IP'],['h','피안타'],['r','실점'],['er','자책'],['bb','볼넷'],['so','삼진']].map(([f,l])=>`<label>${l}<input data-pitch="${f}" type="number" min="0" step="${f==='ip'?'.1':'1'}" value="${p[f]||0}" ${disabled?'disabled':''}></label>`).join('')}</div><div class="plate-result-actions">${[['h','안타'],['so','삼진'],['bb','볼넷'],['hbp','사구'],['hr','홈런'],['out','아웃']].map(([x,l])=>`<button type="button" data-quick-result="${x}" ${disabled?'disabled':''}>${l}</button>`).join('')}</div></article>`).join('')}${disabled?'':`<button class="add-pitcher" type="button" data-add-pitcher="${side}">＋ 투수 추가</button>`}</div>`}
  function stats(a){let ab=0,h=0,tb=0,w=0,r=0,rbi=0;a.forEach(b=>b.pa.forEach(p=>{r+=p.run?1:0;rbi+=+p.rbi||0;const x=p.result;if(!x)return;if(['BB','HBP','SAC'].includes(x)){if(x!=='SAC')w++;return}ab++;if(['1B','2B','3B','HR'].includes(x)){h++;tb+=x==='1B'?1:x==='2B'?2:x==='3B'?3:4}}));return{ab,h,r,rbi,avg:ab?(h/ab).toFixed(3).replace(/^0/,''):'.000',ops:(((ab+w)?(h+w)/(ab+w):0)+(ab?tb/ab:0)).toFixed(3)}}
  const card=(n,s,o='')=>`<article class="team-summary ${o}"><div class="team-summary-head"><strong>${esc(n)}</strong><span>${s.r}득점</span></div><div class="summary-stats">${[['AVG',s.avg],['OPS',s.ops],['AB',s.ab],['H',s.h],['RBI',s.rbi]].map(x=>`<div class="summary-stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div></article>`;
  function summary(){record.ourSummary=stats(record.ours);record.oppSummary=stats(record.opps);$('#scoreSummaryGrid').innerHTML=card(teamName(),record.ourSummary)+card(record.opponent||'상대팀',record.oppSummary,'opponent')}
  function syncHeader(){record.date=$('#scoreGameDate').value;record.opponent=$('#scoreOpponent').value;record.ourRuns=+$('#scoreOurRuns').value||0;record.oppRuns=+$('#scoreOpponentRuns').value||0;summary()}
  function mark(){$('#scoreSaveState').textContent='수정 중';summary()}
  function bindSheet(){$$('.paper-player').forEach(row=>{const arr=row.dataset.side==='ours'?record.ours:record.opps,b=arr[+row.dataset.i],name=$('[data-player-name]',row),num=$('[data-number]',row),pos=$('[data-position]',row);if(name)name.addEventListener('change',()=>{b.name=name.value;const p=rosterPlayers().find(x=>x.name===name.value);if(p){b.number=p.number;b.position=p.position}mark()});if(num)num.addEventListener('input',()=>{b.number=num.value;mark()});if(pos)pos.addEventListener('input',()=>{b.position=pos.value;mark()});$('[data-add-sub]',row)?.addEventListener('click',()=>addSub(row.dataset.side,+row.dataset.i));$$('[data-open-pa]',row).forEach(btn=>btn.addEventListener('click',()=>openPA(row.dataset.side,+row.dataset.i,+btn.dataset.openPa)))});$$('.pitcher-console').forEach(box=>{const arr=box.dataset.ps==='ours'?record.ourPitchers:record.oppPitchers,p=arr[+box.dataset.pi];$$('[data-pitch]',box).forEach(e=>e.addEventListener('input',()=>{p[e.dataset.pitch]=e.type==='number'?+e.value||0:e.value;mark()}));$$('[data-pitch-add]',box).forEach(btn=>btn.addEventListener('click',()=>{p.pitches++;p[btn.dataset.pitchAdd==='strike'?'strikes':'balls']++;renderPitchers();mark()}));$('[data-pitch-undo]',box)?.addEventListener('click',()=>{if(p.pitches){p.pitches--;if(p.balls>p.strikes)p.balls--;else if(p.strikes)p.strikes--;renderPitchers();mark()}});$$('[data-quick-result]',box).forEach(btn=>btn.addEventListener('click',()=>{const x=btn.dataset.quickResult;if(x==='h'||x==='hr')p.h++;if(x==='so')p.so++;if(x==='bb')p.bb++;btn.classList.add('pressed');setTimeout(()=>btn.classList.remove('pressed'),180);mark()}))});$$('[data-add-pitcher]').forEach(b=>b.addEventListener('click',()=>{(b.dataset.addPitcher==='ours'?record.ourPitchers:record.oppPitchers).push(pitcher('구원투수'));renderPitchers();mark()}))}
  function renderPitchers(){const off=!league.editable;$('#ourPitchingTable').innerHTML=pitching('ours',record.ourPitchers,off);$('#opponentPitchingTable').innerHTML=pitching('opps',record.oppPitchers,off);bindSheet()}
  function renderBatters(){const off=!league.editable;$('#ourBattingTable').innerHTML=batting('ours',record.ours,off);$('#opponentBattingTable').innerHTML=batting('opps',record.opps,off);bindSheet();summary()}
  function addSub(side,i){const b=(side==='ours'?record.ours:record.opps)[i],name=prompt(side==='ours'?`교체 선수 이름\n${rosterPlayers().map(p=>`${p.number} ${p.name}`).join(', ')}`:'교체 선수 이름','');if(!name)return;const note=prompt('교체 내용 (예: 5회초 대타, 6회말 좌익수)','')||'';b.subs.push({name,note});renderBatters();mark()}
  function ensureEditor(){if($('#paEditor'))return;document.body.insertAdjacentHTML('beforeend',`<div class="pa-editor-backdrop" id="paEditorBackdrop" hidden></div><section class="pa-editor" id="paEditor" role="dialog" aria-modal="true" hidden><header><div><small id="paEditorPlayer"></small><h2 id="paEditorTitle">타석 기록</h2></div><button type="button" id="closePaEditor">×</button></header><div class="pa-count-control"><div><span>볼</span><button data-count="balls" data-delta="-1">−</button><b id="paBalls">0</b><button data-count="balls" data-delta="1">＋</button></div><div><span>스트라이크</span><button data-count="strikes" data-delta="-1">−</button><b id="paStrikes">0</b><button data-count="strikes" data-delta="1">＋</button></div></div><label class="editor-label">타석 결과<select id="paResult">${results.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><div class="runner-diamond"><button data-base="1">1루</button><button data-base="2">2루</button><button data-base="3">3루</button><button data-run>홈 · 득점</button><span class="diamond-lines"></span></div><label class="editor-label">타점<input id="paRbi" type="number" min="0" max="4"></label><label class="editor-label">주루·상황 메모<input id="paNote" placeholder="도루, 견제사, 폭투 등"></label><button class="primary-action" id="savePaEditor" type="button">타석 기록 적용</button></section>`);$('#closePaEditor').onclick=closePA;$('#paEditorBackdrop').onclick=closePA;$$('[data-count]',$('#paEditor')).forEach(b=>b.onclick=()=>{const pa=currentPA(),f=b.dataset.count;pa[f]=Math.max(0,Math.min(f==='balls'?4:3,pa[f]+Number(b.dataset.delta)));fillPA()});$$('[data-base]',$('#paEditor')).forEach(b=>b.onclick=()=>{const pa=currentPA(),i=+b.dataset.base-1;pa.bases[i]=!pa.bases[i];fillPA()});$('[data-run]',$('#paEditor')).onclick=()=>{const pa=currentPA();pa.run=!pa.run;fillPA()};$('#savePaEditor').onclick=()=>{const pa=currentPA();pa.result=$('#paResult').value;pa.rbi=+$('#paRbi').value||0;pa.note=$('#paNote').value;closePA();renderBatters();mark()}}
  function currentPA(){return(editing.side==='ours'?record.ours:record.opps)[editing.i].pa[editing.j]}
  function fillPA(){const a=editing.side==='ours'?record.ours:record.opps,b=a[editing.i],pa=currentPA();$('#paEditorPlayer').textContent=`${editing.i+1}번 ${b.name||'이름 미정'}`;$('#paEditorTitle').textContent=`${editing.j+1}번째 타석`;$('#paBalls').textContent=pa.balls;$('#paStrikes').textContent=pa.strikes;$('#paResult').value=pa.result;$('#paRbi').value=pa.rbi;$('#paNote').value=pa.note||'';$$('[data-base]',$('#paEditor')).forEach(x=>x.classList.toggle('on',pa.bases[+x.dataset.base-1]));$('[data-run]',$('#paEditor')).classList.toggle('on',pa.run)}
  function openPA(side,i,j){editing={side,i,j};ensureEditor();fillPA();$('#paEditor').hidden=false;$('#paEditorBackdrop').hidden=false}function closePA(){$('#paEditor').hidden=true;$('#paEditorBackdrop').hidden=true}
  function openBook(id){record=normalize((id&&load().find(r=>r.id===id))||fresh());const off=!league.editable;$('#scorebookLeagueName').textContent=league.name;$('#scoreGameDate').value=record.date;$('#scoreOpponent').value=record.opponent;$('#scoreOurRuns').value=record.ourRuns;$('#scoreOpponentRuns').value=record.oppRuns;$('#ourScoreTeamName').textContent=teamName();$('#opponentScoreTeamName').textContent=record.opponent||'상대팀';$('#saveScoreDraft').hidden=off;$('#finishScoreRecord').hidden=off;$$('#screen-scorebook .game-setup-card input').forEach(e=>{e.disabled=off;e.oninput=()=>{syncHeader();$('#opponentScoreTeamName').textContent=record.opponent||'상대팀';mark()}});renderBatters();renderPitchers();summary();screen('scorebook')}
  function persist(done){syncHeader();record.finished=done;const a=load(),i=a.findIndex(r=>r.id===record.id);i<0?a.push(record):a[i]=record;save(a);$('#scoreSaveState').textContent=done?'경기 종료 · 저장됨':'임시 저장됨';if(typeof showToast==='function')showToast(done?'경기 기록과 양 팀 평균을 저장했습니다.':'임시 저장했습니다.')}
  $$('#leagueAccordion .outline-action').forEach((b,i)=>b.addEventListener('click',e=>{e.stopImmediatePropagation();const a=b.closest('article');league={teamKey:typeof selectedTeam!=='undefined'?selectedTeam:'bbat',leagueId:i===0?'seoul':i===1?'hangang':'personal',name:$('strong',a)?.textContent||'리그 기록',editable:i!==1};archive();screen('league-detail')}));
  $('#leagueDetailBack').onclick=()=>screen('league');$('#scorebookBack').onclick=()=>{archive();screen('league-detail')};$('#startGameRecord').onclick=()=>openBook();$('#saveScoreDraft').onclick=()=>persist(false);$('#finishScoreRecord').onclick=()=>{persist(true);archive();screen('league-detail')};$$('.score-tab').forEach(b=>b.onclick=()=>{$$('.score-tab').forEach(x=>x.classList.toggle('active',x===b));$$('[data-score-panel]').forEach(p=>p.hidden=p.dataset.scorePanel!==b.dataset.scoreTab)});
  document.addEventListener('click',event=>{const btn=event.target.closest?.('[data-open-pa]');if(!btn)return;const row=btn.closest('.paper-player');openPA(row.dataset.side,+row.dataset.i,+btn.dataset.openPa)});
})();
