(() => {
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], key="bbat-box-game-records";
  let league={teamKey:"bbat",leagueId:"seoul",name:"서울 일요리그",editable:true}, record=null;
  const load=()=>{try{return JSON.parse(localStorage.getItem(key)||"[]")}catch{return[]}}, save=a=>localStorage.setItem(key,JSON.stringify(a)), esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
  const teamName=()=>{try{return teams[selectedTeam]?.name||"배트조짐"}catch{return"배트조짐"}};
  function screen(name){$$('.app-screen').forEach(s=>{let on=s.dataset.screen===name;s.hidden=!on;s.classList.toggle('active',on)});$$('[data-nav]').forEach(n=>n.classList.toggle('active',n.dataset.nav===(['league-detail','scorebook'].includes(name)?'league':name)));window.scrollTo(0,0)}
  function archive(){let rows=load().filter(r=>r.teamKey===league.teamKey&&r.leagueId===league.leagueId).sort((a,b)=>b.date.localeCompare(a.date));$('#leagueDetailTitle').textContent=league.name;$('#leagueRoleChip').textContent=league.editable?'관리자 · 수정 가능':'보기 전용';$('#startGameRecord').hidden=!league.editable;$('#recordCount').textContent=`기록된 경기 ${rows.length}`;$('#recordedGameList').innerHTML=rows.length?rows.map(r=>`<article class="record-game-card"><div class="record-game-date">${esc(r.date)}<br>${r.finished?'경기 종료':'작성 중'}</div><div class="record-game-match"><strong>${esc(teamName())} vs ${esc(r.opponent||'상대팀')}</strong><span>우리팀 AVG ${r.ourSummary?.avg||'.000'} · 상대팀 AVG ${r.oppSummary?.avg||'.000'}</span></div><div class="record-game-score"><b>${r.ourRuns||0} : ${r.oppRuns||0}</b><button data-record="${r.id}">${league.editable?'기록 수정':'기록 보기'}</button></div></article>`).join(''):'<div class="empty-records"><strong>아직 저장된 경기 기록이 없어요.</strong><p>관리자는 ‘경기 기록’ 버튼으로 첫 기록을 시작할 수 있습니다.</p></div>';$$('[data-record]',$('#recordedGameList')).forEach(b=>b.onclick=()=>openBook(b.dataset.record))}
  function names(){let a=[];try{let games=getUpcomingGames(selectedTeam,league.leagueId),g=games[0],l=g&&lineupState[gameKey(selectedTeam,league.leagueId,g)];if(l?.batting)a=l.batting.map(x=>x.playerName||x.name).filter(Boolean)}catch{}if(!a.length)try{a=rosters[selectedTeam].filter(x=>x.isPlayer!==false).slice(0,9).map(x=>x.name)}catch{}while(a.length<9)a.push(`${a.length+1}번 타자`);return a.slice(0,9)}
  const batter=n=>({name:n,pa:Array.from({length:10},()=>({result:'',pitches:''})),runs:0,rbi:0}), fresh=()=>({id:`game-${Date.now()}`,teamKey:league.teamKey,leagueId:league.leagueId,date:new Date().toISOString().slice(0,10),opponent:'',ourRuns:0,oppRuns:0,finished:false,ours:names().map(batter),opps:Array.from({length:9},(_,i)=>batter(`${i+1}번 타자`)),ourPitchers:[{name:'선발투수'}],oppPitchers:[{name:'상대 선발투수'}]});
  function normalize(r){for(const prop of ['ours','opps']){r[prop]=(r[prop]||[]).map((b,i)=>({...batter(b.name||`${i+1}번 타자`),...b,pa:Array.from({length:10},(_,j)=>b.pa?.[j]||{result:'',pitches:''})}));while(r[prop].length<9)r[prop].push(batter(`${r[prop].length+1}번 타자`))}r.ourPitchers||=[{name:'선발투수'}];r.oppPitchers||=[{name:'상대 선발투수'}];return r}
  const outcomes=[['','—'],['1B','1루타'],['2B','2루타'],['3B','3루타'],['1HR','1점홈런'],['2HR','2점홈런'],['3HR','3점홈런'],['GS','만루홈런'],['BB','볼넷'],['HBP','사구'],['SO','삼진'],['GO','땅볼'],['FO','뜬공'],['FC','야수선택'],['E','실책'],['SAC','희생타']];
  function batting(side,a,disabled){return`<div class="batting-score-table"><div class="score-row header"><span>순번</span><span>선수</span>${Array.from({length:10},(_,i)=>`<span>${i+1}타석<br>결과·투구</span>`).join('')}<span>득점</span><span>타점</span></div>${a.map((b,i)=>`<div class="score-row" data-side="${side}" data-i="${i}"><span class="order-box">${i+1}</span><label class="player-cell"><input data-f="name" value="${esc(b.name)}" ${side==='ours'||disabled?'disabled':''}></label>${b.pa.map((p,j)=>`<label class="pa-cell"><select data-pa="${j}" data-pf="result" ${disabled?'disabled':''}>${outcomes.map(([v,l])=>`<option value="${v}" ${p.result===v?'selected':''}>${l}</option>`).join('')}</select><input data-pa="${j}" data-pf="pitches" value="${esc(p.pitches)}" placeholder="B/S/F/X" ${disabled?'disabled':''}></label>`).join('')}<input class="run-cell" type="number" min="0" data-f="runs" value="${b.runs||0}" ${disabled?'disabled':''}><input class="run-cell" type="number" min="0" data-f="rbi" value="${b.rbi||0}" ${disabled?'disabled':''}></div>`).join('')}</div>`}
  function pitching(side,a,disabled){let f=['name','ip','h','r','er','bb','so'];return`<div class="pitch-row header">${['투수','IP','H','R','ER','BB','K'].map(x=>`<span>${x}</span>`).join('')}</div>${a.map((p,i)=>`<div class="pitch-row" data-ps="${side}" data-pi="${i}">${f.map(x=>`<input data-pitch="${x}" value="${esc(p[x]||'')}" ${disabled?'disabled':''}>`).join('')}</div>`).join('')}`}
  function stats(a){let ab=0,h=0,tb=0,w=0,r=0,rbi=0;a.forEach(b=>{r+=+b.runs||0;rbi+=+b.rbi||0;b.pa.forEach(p=>{let x=p.result;if(!x)return;if(['BB','HBP','SAC'].includes(x)){if(x!=='SAC')w++;return}ab++;if(['1B','2B','3B','1HR','2HR','3HR','GS'].includes(x)){h++;tb+=x==='1B'?1:x==='2B'?2:x==='3B'?3:4}})});return{ab,h,r,rbi,avg:ab?(h/ab).toFixed(3).replace(/^0/,''):'.000',ops:(((ab+w)?(h+w)/(ab+w):0)+(ab?tb/ab:0)).toFixed(3)}}
  const card=(n,s,o='')=>`<article class="team-summary ${o}"><div class="team-summary-head"><strong>${esc(n)}</strong><span>${s.r}득점</span></div><div class="summary-stats">${[['AVG',s.avg],['OPS',s.ops],['AB',s.ab],['H',s.h],['RBI',s.rbi]].map(x=>`<div class="summary-stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div></article>`;
  function summary(){record.ourSummary=stats(record.ours);record.oppSummary=stats(record.opps);$('#scoreSummaryGrid').innerHTML=card(teamName(),record.ourSummary)+card(record.opponent||'상대팀',record.oppSummary,'opponent')}
  function sync(){record.date=$('#scoreGameDate').value;record.opponent=$('#scoreOpponent').value;record.ourRuns=+$('#scoreOurRuns').value||0;record.oppRuns=+$('#scoreOpponentRuns').value||0;$$('[data-side]').forEach(row=>{let b=(row.dataset.side==='ours'?record.ours:record.opps)[+row.dataset.i];$$('[data-f]',row).forEach(e=>b[e.dataset.f]=e.type==='number'?+e.value||0:e.value);$$('[data-pa]',row).forEach(e=>b.pa[+e.dataset.pa][e.dataset.pf]=e.value)});$$('[data-ps]').forEach(row=>{let p=(row.dataset.ps==='ours'?record.ourPitchers:record.oppPitchers)[+row.dataset.pi];$$('[data-pitch]',row).forEach(e=>p[e.dataset.pitch]=e.value)});summary()}
  function openBook(id){record=normalize((id&&load().find(r=>r.id===id))||fresh());let off=!league.editable;$('#scorebookLeagueName').textContent=league.name;$('#scoreGameDate').value=record.date;$('#scoreOpponent').value=record.opponent;$('#scoreOurRuns').value=record.ourRuns;$('#scoreOpponentRuns').value=record.oppRuns;$('#ourScoreTeamName').textContent=teamName();$('#opponentScoreTeamName').textContent=record.opponent||'상대팀';$('#ourBattingTable').innerHTML=batting('ours',record.ours,off);$('#opponentBattingTable').innerHTML=batting('opps',record.opps,off);$('#ourPitchingTable').innerHTML=pitching('ours',record.ourPitchers,off);$('#opponentPitchingTable').innerHTML=pitching('opps',record.oppPitchers,off);$('#saveScoreDraft').hidden=off;$('#finishScoreRecord').hidden=off;$$('#screen-scorebook input,#screen-scorebook select').forEach(e=>e.oninput=()=>{sync();$('#opponentScoreTeamName').textContent=record.opponent||'상대팀';$('#scoreSaveState').textContent='수정 중'});summary();screen('scorebook')}
  function persist(done){sync();record.finished=done;let a=load(),i=a.findIndex(r=>r.id===record.id);i<0?a.push(record):a[i]=record;save(a);$('#scoreSaveState').textContent=done?'경기 종료 · 저장됨':'임시 저장됨';if(typeof showToast==='function')showToast(done?'경기 기록과 양 팀 평균을 저장했습니다.':'임시 저장했습니다.')}
  $$('#leagueAccordion .outline-action').forEach((b,i)=>b.addEventListener('click',e=>{e.stopImmediatePropagation();let a=b.closest('article');league={teamKey:typeof selectedTeam!=='undefined'?selectedTeam:'bbat',leagueId:i===0?'seoul':i===1?'hangang':'personal',name:$('strong',a)?.textContent||'리그 기록',editable:i!==1};archive();screen('league-detail')}));
  $('#leagueDetailBack').onclick=()=>screen('league');$('#scorebookBack').onclick=()=>{archive();screen('league-detail')};$('#startGameRecord').onclick=()=>openBook();$('#saveScoreDraft').onclick=()=>persist(false);$('#finishScoreRecord').onclick=()=>{persist(true);archive();screen('league-detail')};$$('.score-tab').forEach(b=>b.onclick=()=>{$$('.score-tab').forEach(x=>x.classList.toggle('active',x===b));$$('[data-score-panel]').forEach(p=>p.hidden=p.dataset.scorePanel!==b.dataset.scoreTab)});
})();
