create extension if not exists pgcrypto with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (username ~ '^[a-z0-9_]{3,20}$'),
  full_name text not null check (char_length(full_name) between 1 and 20),
  nickname text not null check (char_length(nickname) between 1 and 16),
  status text not null default 'active' check (status in ('active', 'suspended')),
  is_platform_host boolean not null default false,
  must_change_password boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_username_lower_key
  on public.profiles (lower(username));

create unique index if not exists one_platform_host
  on public.profiles ((is_platform_host)) where is_platform_host;

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.team_members (
  team_id uuid not null references public.teams(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member'
    check (role in ('host', 'admin', 'manager', 'scorer', 'member')),
  status text not null default 'active'
    check (status in ('active', 'suspended')),
  joined_at timestamptz not null default now(),
  primary key (team_id, user_id)
);

create unique index if not exists one_host_per_team
  on public.team_members (team_id) where role = 'host';

create table if not exists public.team_invites (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  code_hash text not null unique,
  role text not null default 'member'
    check (role in ('host', 'admin', 'manager', 'scorer', 'member')),
  max_uses integer not null default 1 check (max_uses between 1 and 100),
  uses_count integer not null default 0 check (uses_count >= 0),
  expires_at timestamptz not null,
  active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.account_audit_log (
  id bigint generated by default as identity primary key,
  team_id uuid references public.teams(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  target_id uuid references public.profiles(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.teams (id, slug, name)
values ('00000000-0000-4000-8000-000000000023', 'bbat', '배트조짐')
on conflict (slug) do update set name = excluded.name;

create or replace function public.invite_code_hash(p_code text)
returns text
language sql
immutable
set search_path = public, extensions
as $$
  select encode(digest(upper(trim(coalesce(p_code, ''))), 'sha256'), 'hex');
$$;

create or replace function public.is_team_manager(p_team_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.team_members tm
    join public.profiles p on p.id = tm.user_id
    where tm.team_id = p_team_id
      and tm.user_id = auth.uid()
      and tm.role in ('host', 'admin', 'manager')
      and tm.status = 'active'
      and p.status = 'active'
  );
$$;

create or replace function public.shares_team_with(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.team_members mine
    join public.team_members theirs on theirs.team_id = mine.team_id
    where mine.user_id = auth.uid()
      and theirs.user_id = p_user_id
      and mine.status = 'active'
      and theirs.status = 'active'
  );
$$;

create or replace function public.username_is_available(p_username text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select lower(trim(coalesce(p_username, ''))) ~ '^[a-z0-9_]{3,20}$'
    and not exists (
      select 1 from public.profiles
      where lower(username) = lower(trim(p_username))
    );
$$;

create or replace function public.invite_is_valid(p_code text)
returns boolean
language sql
stable
security definer
set search_path = public, extensions
as $$
  select exists (
    select 1
    from public.team_invites
    where code_hash = public.invite_code_hash(p_code)
      and active
      and expires_at > now()
      and uses_count < max_uses
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_username text := lower(trim(coalesce(new.raw_user_meta_data ->> 'username', '')));
  v_name text := trim(coalesce(new.raw_user_meta_data ->> 'full_name', ''));
  v_nickname text := trim(coalesce(new.raw_user_meta_data ->> 'nickname', ''));
  v_invite_code text := trim(coalesce(new.raw_user_meta_data ->> 'invite_code', ''));
  v_invite public.team_invites%rowtype;
begin
  if v_username !~ '^[a-z0-9_]{3,20}$' then
    raise exception 'INVALID_USERNAME';
  end if;
  if char_length(v_name) not between 1 and 20 then
    raise exception 'INVALID_NAME';
  end if;
  if char_length(v_nickname) not between 1 and 16 then
    raise exception 'INVALID_NICKNAME';
  end if;

  select * into v_invite
  from public.team_invites
  where code_hash = public.invite_code_hash(v_invite_code)
    and active
    and expires_at > now()
    and uses_count < max_uses
  for update;

  if v_invite.id is null then
    raise exception 'INVALID_INVITE';
  end if;

  insert into public.profiles (id, username, full_name, nickname, is_platform_host)
  values (new.id, v_username, v_name, v_nickname, v_invite.role = 'host');

  insert into public.team_members (team_id, user_id, role)
  values (v_invite.team_id, new.id, v_invite.role);

  update public.team_invites
  set uses_count = uses_count + 1,
      active = case when uses_count + 1 >= max_uses then false else active end
  where id = v_invite.id;

  if v_invite.role = 'host' then
    update public.team_invites
    set active = false
    where team_id = v_invite.team_id and role = 'host';
  end if;

  insert into public.account_audit_log (team_id, actor_id, target_id, action, details)
  values (v_invite.team_id, new.id, new.id, 'account_joined', jsonb_build_object('role', v_invite.role));

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.update_my_profile(p_full_name text, p_nickname text)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
begin
  if auth.uid() is null then raise exception 'NOT_AUTHENTICATED'; end if;
  if char_length(trim(p_full_name)) not between 1 and 20 then raise exception 'INVALID_NAME'; end if;
  if char_length(trim(p_nickname)) not between 1 and 16 then raise exception 'INVALID_NICKNAME'; end if;

  update public.profiles
  set full_name = trim(p_full_name), nickname = trim(p_nickname), updated_at = now()
  where id = auth.uid() and status = 'active'
  returning * into v_profile;
  return v_profile;
end;
$$;

create or replace function public.create_team_invite(
  p_role text default 'member',
  p_expires_days integer default 30,
  p_max_uses integer default 1
)
returns table(code text, expires_at timestamptz, max_uses integer, role text)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_team_id uuid := '00000000-0000-4000-8000-000000000023';
  v_code text;
  v_expires_at timestamptz;
  v_caller_role text;
  v_editor_count integer;
  v_reserved_editor_slots integer;
begin
  select tm.role into v_caller_role
  from public.team_members tm
  where tm.team_id = v_team_id
    and tm.user_id = auth.uid()
    and tm.status = 'active';

  if v_caller_role not in ('host', 'admin', 'manager') then raise exception 'NOT_AUTHORIZED'; end if;
  if p_role not in ('admin', 'manager', 'scorer', 'member') then raise exception 'INVALID_ROLE'; end if;
  if v_caller_role = 'manager' and p_role in ('admin', 'manager') then raise exception 'NOT_AUTHORIZED'; end if;
  if v_caller_role = 'admin' and p_role = 'admin' then raise exception 'HOST_REQUIRED'; end if;
  if p_expires_days not between 1 and 90 then raise exception 'INVALID_EXPIRY'; end if;
  if p_max_uses not between 1 and 20 then raise exception 'INVALID_USES'; end if;

  if p_role in ('admin', 'manager', 'scorer') then
    select count(*) into v_editor_count
    from public.team_members
    where team_id = v_team_id
      and role in ('admin', 'manager', 'scorer')
      and status = 'active';

    select coalesce(sum(max_uses - uses_count), 0) into v_reserved_editor_slots
    from public.team_invites
    where team_id = v_team_id
      and role in ('admin', 'manager', 'scorer')
      and active
      and expires_at > now()
      and uses_count < max_uses;

    if v_editor_count + v_reserved_editor_slots + p_max_uses > 5 then
      raise exception 'MAX_EDITORS_REACHED';
    end if;
  end if;

  v_code := 'BBAT-' || upper(substr(encode(gen_random_bytes(8), 'hex'), 1, 12));
  v_expires_at := now() + make_interval(days => p_expires_days);

  insert into public.team_invites (team_id, code_hash, role, max_uses, expires_at, created_by)
  values (v_team_id, public.invite_code_hash(v_code), p_role, p_max_uses, v_expires_at, auth.uid());

  insert into public.account_audit_log (team_id, actor_id, action, details)
  values (v_team_id, auth.uid(), 'invite_created', jsonb_build_object('role', p_role, 'max_uses', p_max_uses));

  return query select v_code, v_expires_at, p_max_uses, p_role;
end;
$$;

create or replace function public.list_team_members()
returns table(
  user_id uuid,
  username text,
  full_name text,
  nickname text,
  role text,
  status text,
  joined_at timestamptz,
  must_change_password boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_team_id uuid := '00000000-0000-4000-8000-000000000023';
begin
  if not public.is_team_manager(v_team_id) then raise exception 'NOT_AUTHORIZED'; end if;
  return query
    select p.id, p.username, p.full_name, p.nickname, tm.role, tm.status,
           tm.joined_at, p.must_change_password
    from public.team_members tm
    join public.profiles p on p.id = tm.user_id
    where tm.team_id = v_team_id
    order by case tm.role when 'host' then 0 when 'admin' then 1 when 'manager' then 2 when 'scorer' then 3 else 4 end,
             p.full_name;
end;
$$;

create or replace function public.set_team_member_role(p_user_id uuid, p_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_team_id uuid := '00000000-0000-4000-8000-000000000023';
  v_my_role text;
  v_target_role text;
begin
  select role into v_my_role from public.team_members
  where team_id = v_team_id and user_id = auth.uid() and status = 'active';
  select role into v_target_role from public.team_members
  where team_id = v_team_id and user_id = p_user_id;

  if v_my_role not in ('host', 'admin') then raise exception 'NOT_AUTHORIZED'; end if;
  if p_role not in ('admin', 'manager', 'scorer', 'member') then raise exception 'INVALID_ROLE'; end if;
  if v_target_role = 'host' then raise exception 'HOST_ROLE_LOCKED'; end if;
  if v_my_role = 'admin' and (v_target_role = 'admin' or p_role = 'admin') then raise exception 'HOST_REQUIRED'; end if;

  update public.team_members set role = p_role
  where team_id = v_team_id and user_id = p_user_id;

  insert into public.account_audit_log (team_id, actor_id, target_id, action, details)
  values (v_team_id, auth.uid(), p_user_id, 'member_role_changed', jsonb_build_object('from', v_target_role, 'to', p_role));
end;
$$;

create or replace function public.set_team_member_status(p_user_id uuid, p_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_team_id uuid := '00000000-0000-4000-8000-000000000023';
  v_my_role text;
  v_target_role text;
begin
  select role into v_my_role from public.team_members
  where team_id = v_team_id and user_id = auth.uid() and status = 'active';
  select role into v_target_role from public.team_members
  where team_id = v_team_id and user_id = p_user_id;

  if v_my_role not in ('host', 'admin') then raise exception 'NOT_AUTHORIZED'; end if;
  if p_status not in ('active', 'suspended') then raise exception 'INVALID_STATUS'; end if;
  if v_target_role = 'host' or p_user_id = auth.uid() then raise exception 'PROTECTED_ACCOUNT'; end if;
  if v_my_role = 'admin' and v_target_role = 'admin' then raise exception 'HOST_REQUIRED'; end if;

  update public.team_members set status = p_status
  where team_id = v_team_id and user_id = p_user_id;
  update public.profiles set status = p_status, updated_at = now()
  where id = p_user_id;

  insert into public.account_audit_log (team_id, actor_id, target_id, action, details)
  values (v_team_id, auth.uid(), p_user_id, 'member_status_changed', jsonb_build_object('to', p_status));
end;
$$;

create or replace function public.enforce_team_editor_limit()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_editor_count integer;
begin
  if new.status = 'active' and new.role in ('admin', 'manager', 'scorer') then
    select count(*) into v_editor_count
    from public.team_members tm
    where tm.team_id = new.team_id
      and tm.role in ('admin', 'manager', 'scorer')
      and tm.status = 'active'
      and tm.user_id <> new.user_id;

    if v_editor_count >= 5 then
      raise exception 'MAX_EDITORS_REACHED';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_team_editor_limit_trigger on public.team_members;
create trigger enforce_team_editor_limit_trigger
  before insert or update of role, status on public.team_members
  for each row execute procedure public.enforce_team_editor_limit();

alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.team_invites enable row level security;
alter table public.account_audit_log enable row level security;

drop policy if exists profiles_select_team on public.profiles;
create policy profiles_select_team on public.profiles for select to authenticated
using (id = auth.uid() or public.shares_team_with(id));

drop policy if exists teams_select_member on public.teams;
create policy teams_select_member on public.teams for select to authenticated
using (exists (
  select 1 from public.team_members tm
  where tm.team_id = teams.id and tm.user_id = auth.uid() and tm.status = 'active'
));

drop policy if exists team_members_select on public.team_members;
create policy team_members_select on public.team_members for select to authenticated
using (user_id = auth.uid() or public.is_team_manager(team_id));

drop policy if exists team_invites_manager_select on public.team_invites;
create policy team_invites_manager_select on public.team_invites for select to authenticated
using (public.is_team_manager(team_id));

drop policy if exists audit_manager_select on public.account_audit_log;
create policy audit_manager_select on public.account_audit_log for select to authenticated
using (public.is_team_manager(team_id));

revoke all on public.profiles, public.teams, public.team_members, public.team_invites, public.account_audit_log from anon;
grant select on public.profiles, public.teams, public.team_members to authenticated;
grant select on public.team_invites, public.account_audit_log to authenticated;

grant execute on function public.username_is_available(text) to anon, authenticated;
grant execute on function public.invite_is_valid(text) to anon, authenticated;
grant execute on function public.update_my_profile(text, text) to authenticated;
grant execute on function public.create_team_invite(text, integer, integer) to authenticated;
grant execute on function public.list_team_members() to authenticated;
grant execute on function public.set_team_member_role(uuid, text) to authenticated;
grant execute on function public.set_team_member_status(uuid, text) to authenticated;
